apiVersion: v1
data:
  admin-jwt-secret: dFE4c24yNjd6UXVZc2w0MQ==
  app-host: MC4wLjAuMA==
  database-host: MTAuNTEuNDkuMw==
  mysql-password: aGFxaEdpUER3TXpzQ2Nhcg==
kind: Secret
metadata:
  name: new-backend
type: Opaque
