---
version: '3'
services:

    frontend:
        build: frontend/
        ports:
            - 3000:3000
        environment:
            API_URL: http://35.183.127.62:1337
            DOCKER_CLIENT_TIMEOUT: 120
            COMPOSE_HTTP_TIMEOUT: 120
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app

    backend:
        image: strapi/strapi
        restart: unless-stopped
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_NAME: strapi
            DATABASE_HOST: mariadb
            DATABASE_PORT: 3306
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
        volumes:
            - ./backend:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - mariadb
        networks:
            - eqx-app

    mariadb:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: strapi
          MYSQL_DATABASE: strapi
          MYSQL_USER: strapi
          MYSQL_PASSWORD: strapi
        volumes:
            - dataDB:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - eqx-app
volumes:
    dataDB:

networks:
    eqx-app:
